name: CI download from before runner (Better)
on:
  workflow_dispatch:
    inputs:
      artifact-id:
        description: 'download artifact from before runner id'
        required: true
        default: '12153076022'
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.GH_TOKEN }} > ghtoken.txt
      - run: sudo gh auth login --with-token < ghtoken.txt
      - run: rm ghtoken.txt
      
      - run: chmod +x ./setup-ssh
      - run: sudo mkdir /mnt/runner-will-upload
      - run: sudo mkdir /mnt/downloaded-from-before
      - run: sudo mkdir /mnt/running
      - run: sudo rm /mnt/DATALOSS_WARNING_README.txt
      
      - run: sudo apt-get update
      - run: sudo apt-get install pv pbzip2 systemd-container debootstrap nano -y

      - run: sudo gh run download ${{ github.event.inputs.LINK }} --dir /mnt/downloaded-from-before --repo lingyicute2323/Action-ssh
      - run: sudo tar --use-compress-program=pbzip2 -xf /mnt/downloaded-from-before/arts/ubuntu.tar.bz2 -C /mnt/running
 
      - run: $GITHUB_WORKSPACE/setup-ssh
        shell: bash

      - run: sudo -i
      - run: cd /mnt/running
      - run: tar --use-compress-program=pbzip2 -cf ubuntu.tar.bz2 ubuntu/
      - run: cp ubuntu.tar.bz2 /mnt/runner-will-upload/

      - run: tree -L 2 /mnt
      - run: exit
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: arts
          path: /mnt/runner-will-upload/*
